### ISSUE TITLE
Mesh - Offset distance not being applied

### ISSUE THREAD

**Issue by devngc** [ladybug-tools/ladybug-rhino#116]
Hi @chriswmackey,
[This](https://discourse.ladybug.tools/t/incident-radiation-using-mesh-geometry-error/11891/2?u=devang) shows a bug in the ladybug rhino library. I tested the file provided by the user and I was able to recreate the error. Following is why this error appears.

We're using to `to_joined_gridded_mesh3d` method from `togeometry` module. You will see [here](https://github.com/ladybug-tools/ladybug-rhino/blob/master/ladybug_rhino/togeometry.py#L222) that the offset distance is not being applied when the geometry is a **Mesh**. The offset distance will be applied if the geometry was a **Brep**.

I wanted to share this with you before I spend time on it. I am happy to look into it for a fix.

**Comment by chriswmackey** [comment]
This was fixed via https://github.com/ladybug-tools/ladybug-grasshopper/pull/134
