### ISSUE TITLE
to_linesegment3d using wrong constructor?

### ISSUE THREAD

**Issue by PH-Tools** [ladybug-tools/ladybug-rhino#131]
in togeometry.py

line 93, inside `def to_linesegment3d(line)`:

I think this method should be calling the LineSegment3D.from_end_points() constructor (point, 
 point) rather than the default constructor (point, vector)  ?

so: 
`def to_linesegment3d(line):
    """Ladybug LineSegment3D from Rhino LineCurve."""
    return LineSegment3D.**from_end_points**(
        to_point3d(line.PointAtStart), to_point3d(line.PointAtEnd))`

**Comment by chriswmackey** [comment]
Thank you for finding and reporting this, @PH-Tools .  Sorry that it took me until now to see this issue and fix it.
