### ISSUE TITLE
Add a method to produce a popup window message

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/ladybug-rhino#224]
I think there are a few places where a popup message will be particularly useful to prevent users from misusing certain workflows. One of them would be to remind users to restart after running the versioner as noted here:
https://discourse.ladybug.tools/t/input-geo-is-not-a-closed-volume/13488/15

I remember that there's a way to make these popup messages with IronPython because Legacy honeybee would give them whenever you overwrote a certain object in you standards library. So I should look there for a sample of how to do this.

**Comment by mostaphaRoudsari** [comment]
This might save you some time looking it up:

https://github.com/ladybug-tools/honeybee-legacy/blob/bd62af4862fe022801fb87dbc8794fdf1dff73a9/src/Honeybee_Honeybee.py#L909-L925

**Comment by chriswmackey** [comment]
This has been addressed!
